name: ios_deps

on:
  - push
  - pull_request

jobs:
  build_ios_deps:
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Prepare
        run: |
          echo "REPDIR=$(pwd)" >> $GITHUB_ENV
          brew install nasm m4 autoconf automake libtool

      - name: Download/clone sources
        run: |
          source deps.sh
          source angle.sh
          mkdir $REPDIR/sources
          cd $REPDIR/sources
          download_ios_deps
          clone_ios_angle $REPDIR/data

      - name: Build deps iPhone
        run: |
          source deps.sh
          mkdir $REPDIR/iphone_deps
          cd $REPDIR/iphone_deps
          untar_ios_deps $REPDIR/sources
          build_ios_deps iPhoneOS 18.2 16.2 $REPDIR/ios_deps/iPhoneOS

      - name: Build ANGLE for iPhone
        run: |
          source angle.sh
          cd $REPDIR/sources
          build_ios_angle iPhoneOS 18.2 16.2 $REPDIR/ios_deps/iPhoneOS $REPDIR/data

      - name: Build deps iPhoneSimulator
        run: |
          source deps.sh
          mkdir $REPDIR/iphonesimulator_deps
          cd $REPDIR/iphonesimulator_deps
          untar_ios_deps $REPDIR/sources
          build_ios_deps iPhoneSimulator 18.2 16.2 $REPDIR/ios_deps/iPhoneSimulator

      - name: Build ANGLE for iPhoneSimulator
        run: |
          source angle.sh
          cd $REPDIR/sources
          build_ios_angle iPhoneSimulator 18.2 16.2 $REPDIR/ios_deps/iPhoneSimulator $REPDIR/data

      - name: Create archive from iPhone and iPhoneSimulator deps
        run: |
          tar -czvf ios_deps.tar.gz ios_deps

      - name: Upload deps
        uses: actions/upload-artifact@v4
        with:
          name: ios_deps
          path: ./ios_deps.tar.gz

      - name: Upload Release Asset
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./macos_deps.tar.gz
          asset_name: macos_deps.tar.gz
          tag: latest
