name: ios_deps

on:
  - push
  - pull_request

jobs:
  build_ios_deps:
    strategy:
      matrix:
        osver: [18.2]
        xcodever: [16.2]
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Prepare deps build for iOS ${{matrix.osver}}
        run: |
          echo "REPDIR=$(pwd)" >> $GITHUB_ENV
          echo "osver=${{matrix.osver}}" >> $GITHUB_ENV
          echo "xcodever=${{matrix.xcodever}}" >> $GITHUB_ENV
          brew install nasm m4 autoconf automake libtool

      - name: Download/clone sources
        run: |
          source deps.sh
          source angle.sh
          mkdir $REPDIR/sources
          cd $REPDIR/sources
          download_ios_deps
          clone_ios_angle $REPDIR/data

      - name: Build deps iPhone
        run: |
          source deps.sh
          mkdir $REPDIR/iphone${osver}_deps
          cd $REPDIR/iphone${osver}_deps
          untar_ios_deps $REPDIR/sources
          build_ios_deps iPhoneOS "$osver" "$xcodever" $REPDIR/ios${osver}_deps/iPhoneOS

      - name: Build ANGLE for iPhone
        run: |
          source angle.sh
          cd $REPDIR/sources
          build_ios_angle iPhoneOS "$osver" "$xcodever" $REPDIR/ios${osver}_deps/iPhoneOS $REPDIR/data

      - name: Build deps iPhoneSimulator
        run: |
          source deps.sh
          mkdir $REPDIR/iphonesimulator${osver}_deps
          cd $REPDIR/iphonesimulator${osver}_deps
          untar_ios_deps $REPDIR/sources
          build_ios_deps iPhoneSimulator "$osver" "$xcodever" $REPDIR/ios${osver}_deps/iPhoneSimulator

      - name: Build ANGLE for iPhoneSimulator
        run: |
          source angle.sh
          cd $REPDIR/sources
          build_ios_angle iPhoneSimulator "$osver" "$xcodever" $REPDIR/ios${osver}_deps/iPhoneSimulator $REPDIR/data

      - name: Create archive from iPhone and iPhoneSimulator deps
        run: |
          tar -czvf ios${osver}_deps.tar.gz ios${osver}_deps

      - name: Upload deps
        uses: actions/upload-artifact@v4
        with:
          name: ios${{matrix.osver}}_deps
          path: ./ios${{matrix.osver}}_deps.tar.gz

      - name: Upload Release Asset
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./ios${{matrix.osver}}_deps.tar.gz
          asset_name: ios${{matrix.osver}}_deps.tar.gz
          overwrite: true
          tag: latest
